### ISSUE TITLE
[Bug] Breadcrumbs to improve navigability

### ISSUE THREAD

**Issue by dartar** [chanzuckerberg/open-science#68]
Not really a bug but a suggestion to **improve the navigability of the website**. When visiting or landing on a subpage like the Dryad overview, it would be useful for me to have a navigation menu at the top allowing me to navigate the parent pages.

**Comment by k8hertweck** [comment]
Thanks so much for this feedback!

I currently keep nav help to a minimum to maximize screen space for other content, with the main sections (Protocols, Software and code, Data, Preprints and publications) of the website listed on the left side (or top, depending on how the web browser is sized):

<img width="708" alt="Screen Shot 2021-11-22 at 11 07 33 AM" src="https://user-images.githubusercontent.com/1678233/142923775-dd2f8a4b-09bf-48f2-b447-c8e7e4b18ae2.png">

Are you thinking we need to list the subsections for each main section on all pages within that category? This is what the subsections for the Data section look like, for example:

<img width="666" alt="Screen Shot 2021-11-22 at 11 37 19 AM" src="https://user-images.githubusercontent.com/1678233/142924679-545bf023-3258-4efb-b536-83b80aad8021.png">

**Comment by k8hertweck** [comment]
Another option: [create sitemap](https://github.com/jekyll/jekyll-sitemap).

Other technical solutions may be possible using jekyll categories? May relate to #21

**Comment by k8hertweck** [comment]
After consultation with Carly, add overview on main page and/or sitemap, and make it searchable
